"""macOS "System Data" knowledge base.

Defines the catalog of locations that traditional disk tools hide inside the
opaque "System Data" bucket, a heuristic deletability score for each, the rules
to classify an arbitrary path into a category, and the protected-path guard that
prevents catastrophic deletions.
"""
import os
from pathlib import Path

HOME = str(Path.home())


def _h(p: str) -> str:
    return os.path.expanduser(p)


# Each category:
#   key, label, description (what it is), paths (concrete roots),
#   base_score (1-10 deletability; 10 = definitely safe), regenerates (bool),
#   caveat (what you lose / risk), icon
CATEGORIES = [
    {
        "key": "xcode_derived_data",
        "label": "Xcode DerivedData",
        "description": "Intermediate build products, indexes and module caches Xcode creates while compiling. Pure cache.",
        "paths": [_h("~/Library/Developer/Xcode/DerivedData")],
        "base_score": 9,
        "regenerates": True,
        "caveat": "Next build will be slower (full rebuild). Nothing is lost.",
        "icon": "hammer",
    },
    {
        "key": "xcode_device_support",
        "label": "iOS/watchOS Device Support",
        "description": "Symbol caches Xcode downloads for each iOS/watchOS/tvOS device & version you've connected for debugging.",
        "paths": [
            _h("~/Library/Developer/Xcode/iOS DeviceSupport"),
            _h("~/Library/Developer/Xcode/watchOS DeviceSupport"),
            _h("~/Library/Developer/Xcode/tvOS DeviceSupport"),
        ],
        "base_score": 8,
        "regenerates": True,
        "caveat": "Re-downloaded automatically next time you attach that device/OS version.",
        "icon": "iphone",
    },
    {
        "key": "core_simulator",
        "label": "iOS Simulators & Caches",
        "description": "CoreSimulator device images, runtimes and caches used by the iOS Simulator. Often tens of GB.",
        "paths": [
            _h("~/Library/Developer/CoreSimulator/Devices"),
            _h("~/Library/Developer/CoreSimulator/Caches"),
        ],
        "base_score": 7,
        "regenerates": True,
        "caveat": "Removes simulator devices/state. Recreated by Xcode; large runtimes re-download.",
        "icon": "device-mobile",
    },
    {
        "key": "xcode_archives",
        "label": "Xcode Archives",
        "description": "Saved .xcarchive builds you produced for App Store / ad-hoc distribution.",
        "paths": [_h("~/Library/Developer/Xcode/Archives")],
        "base_score": 4,
        "regenerates": False,
        "caveat": "These are real release artifacts. Keep any you may still ship or need dSYMs for.",
        "icon": "archive",
    },
    {
        "key": "xcode_misc",
        "label": "Xcode Caches & Logs",
        "description": "Xcode user caches, Previews, logs and the Xcode app cache.",
        "paths": [
            _h("~/Library/Developer/Xcode/UserData/Previews"),
            _h("~/Library/Developer/Xcode/Products"),
            _h("~/Library/Caches/com.apple.dt.Xcode"),
            _h("~/Library/Developer/CoreSimulator/Caches/dyld"),
        ],
        "base_score": 8,
        "regenerates": True,
        "caveat": "Regenerated by Xcode.",
        "icon": "hammer",
    },
    {
        "key": "ios_backups",
        "label": "iPhone/iPad Backups",
        "description": "Full local backups of iOS devices made by Finder/iTunes (MobileSync).",
        "paths": [_h("~/Library/Application Support/MobileSync/Backup")],
        "base_score": 3,
        "regenerates": False,
        "caveat": "DANGER: these are your only local device backups unless you have iCloud/another copy.",
        "icon": "shield",
    },
    {
        "key": "user_caches",
        "label": "Application Caches",
        "description": "Per-app caches in your user Library. Apps rebuild these on demand.",
        "paths": [_h("~/Library/Caches")],
        "base_score": 8,
        "regenerates": True,
        "caveat": "Apps rebuild caches; some may need to re-download data.",
        "icon": "stack",
    },
    {
        "key": "container_caches",
        "label": "Sandboxed App Caches",
        "description": "Caches inside sandboxed app containers (Mail, Safari, App Store apps, etc.).",
        "paths": [_h("~/Library/Containers")],
        "base_score": 7,
        "regenerates": True,
        "caveat": "Only cache subfolders are junk; container also holds app data. Delete with care.",
        "icon": "box",
    },
    {
        "key": "logs",
        "label": "Logs & Diagnostic Reports",
        "description": "Application logs, crash reports and diagnostic dumps.",
        "paths": [
            _h("~/Library/Logs"),
            _h("~/Library/Logs/DiagnosticReports"),
        ],
        "base_score": 8,
        "regenerates": True,
        "caveat": "Lose historical crash/diagnostic logs (rarely needed).",
        "icon": "file-text",
    },
    {
        "key": "saved_state",
        "label": "Saved Application State",
        "description": "Window/restore state macOS keeps so apps reopen where you left off.",
        "paths": [_h("~/Library/Saved Application State")],
        "base_score": 8,
        "regenerates": True,
        "caveat": "Apps simply reopen fresh instead of restoring previous windows.",
        "icon": "window",
    },
    {
        "key": "trash",
        "label": "Trash",
        "description": "Files you already moved to the Trash but never emptied.",
        "paths": [_h("~/.Trash")],
        "base_score": 9,
        "regenerates": False,
        "caveat": "Final removal of already-trashed files.",
        "icon": "trash",
    },
    {
        "key": "homebrew_cache",
        "label": "Homebrew Cache",
        "description": "Downloaded bottles/installers Homebrew keeps after installing.",
        "paths": [
            _h("~/Library/Caches/Homebrew"),
            "/opt/homebrew/var/cache",
        ],
        "base_score": 9,
        "regenerates": True,
        "caveat": "Re-downloaded if needed. `brew cleanup` does the same.",
        "icon": "beer",
    },
    {
        "key": "package_caches",
        "label": "Dev Package Caches",
        "description": "Download caches for npm, yarn, pip, CocoaPods, Gradle and Maven.",
        "paths": [
            _h("~/.npm/_cacache"),
            _h("~/Library/Caches/Yarn"),
            _h("~/.cache/yarn"),
            _h("~/Library/Caches/pip"),
            _h("~/Library/Caches/CocoaPods"),
            _h("~/.cocoapods/repos"),
            _h("~/.gradle/caches"),
        ],
        "base_score": 8,
        "regenerates": True,
        "caveat": "Packages re-download on next install. Maven ~/.m2 may hold private artifacts.",
        "icon": "package",
    },
    {
        "key": "docker",
        "label": "Docker Data",
        "description": "Docker Desktop disk image holding images, containers and volumes.",
        "paths": [
            _h("~/Library/Containers/com.docker.docker/Data"),
            _h("~/.docker"),
        ],
        "base_score": 5,
        "regenerates": True,
        "caveat": "Holds your images AND named volumes (data!). Prefer `docker system prune` over deleting.",
        "icon": "ship",
    },
    {
        "key": "node_modules",
        "label": "node_modules / build output",
        "description": "Reinstallable dependency and build folders inside projects (node_modules, dist, build, target, .next, .gradle).",
        "paths": [],  # discovered by name while scanning a project tree
        "base_score": 7,
        "regenerates": True,
        "caveat": "Restored by re-running install/build in that project.",
        "icon": "folder-code",
    },
    {
        "key": "mail_downloads",
        "label": "Mail Attachments Cache",
        "description": "Attachments Mail.app downloaded and cached.",
        "paths": [
            _h("~/Library/Containers/com.apple.mail/Data/Library/Mail Downloads"),
        ],
        "base_score": 7,
        "regenerates": True,
        "caveat": "Re-downloaded from the server when you reopen the message.",
        "icon": "mail",
    },
    {
        "key": "vm_swap",
        "label": "VM Swap / Sleep Image",
        "description": "System-managed virtual-memory swap files and the sleepimage.",
        "paths": ["/System/Volumes/VM"],
        "base_score": 1,
        "regenerates": True,
        "caveat": "PROTECTED by macOS (SIP). Do not delete manually; the OS manages this.",
        "icon": "cpu",
    },
    {
        "key": "downloads",
        "label": "Downloads Folder",
        "description": "Your ~/Downloads folder — often full of forgotten installers and archives.",
        "paths": [_h("~/Downloads")],
        "base_score": 5,
        "regenerates": False,
        "caveat": "These are YOUR files. Review before deleting.",
        "icon": "download",
    },
]

CATEGORY_BY_KEY = {c["key"]: c for c in CATEGORIES}

# Default scan target = curated system-data categories (skip user Downloads,
# node_modules discovery and SIP-protected VM by default; user can add them).
DEFAULT_SCAN_KEYS = [
    "xcode_derived_data", "xcode_device_support", "core_simulator", "xcode_archives",
    "xcode_misc", "ios_backups", "user_caches", "container_caches", "logs",
    "saved_state", "trash", "homebrew_cache", "package_caches", "docker",
    "mail_downloads", "vm_swap",
]

# Directory-name patterns that mark a folder as reinstallable dev junk, anywhere.
DEV_JUNK_DIRNAMES = {
    "node_modules": ("node_modules", 7),
    "DerivedData": ("xcode_derived_data", 9),
    ".next": ("node_modules", 8),
    "dist": ("node_modules", 6),
    "build": ("node_modules", 6),
    "target": ("node_modules", 6),
    ".gradle": ("package_caches", 8),
    ".cxx": ("node_modules", 8),
    "Pods": ("package_caches", 7),
    "__pycache__": ("node_modules", 9),
    ".pytest_cache": ("node_modules", 9),
    ".mypy_cache": ("node_modules", 9),
}

# ---- Protected paths: deletion of these (or their ancestors) is refused. ----
PROTECTED_PREFIXES = [
    "/System", "/usr", "/bin", "/sbin", "/etc", "/var/db", "/private/var/db",
    "/Library/Apple", "/cores", "/dev", "/Network", "/.vol",
    "/System/Volumes/VM",
    _h("~/Library/Keychains"),
    _h("~/Library/Preferences"),
]

# Exact paths that may never be deleted (volume roots, home, etc.).
PROTECTED_EXACT = {
    "/", "/Users", "/Applications", "/Library", "/System/Volumes/Data",
    "/opt", "/opt/homebrew", "/private", "/var", "/tmp",
    HOME, str(Path.home()),
    _h("~/Library"), _h("~/Documents"), _h("~/Desktop"),
}


def classify(path: str, is_dir: bool) -> str:
    """Classify an absolute path into a category key, or '' if unknown."""
    name = os.path.basename(path.rstrip("/"))
    if is_dir and name in DEV_JUNK_DIRNAMES:
        return DEV_JUNK_DIRNAMES[name][0]
    best = ""
    best_len = -1
    for cat in CATEGORIES:
        for root in cat["paths"]:
            root = root.rstrip("/")
            if path == root or path.startswith(root + "/"):
                if len(root) > best_len:
                    best, best_len = cat["key"], len(root)
    return best


def base_score_for(path: str, is_dir: bool, category: str) -> int:
    name = os.path.basename(path.rstrip("/"))
    if is_dir and name in DEV_JUNK_DIRNAMES:
        return DEV_JUNK_DIRNAMES[name][1]
    cat = CATEGORY_BY_KEY.get(category)
    return cat["base_score"] if cat else 5


def existing_targets(keys):
    """Return [(category_key, path)] for every catalog path that exists on disk."""
    out = []
    for key in keys:
        cat = CATEGORY_BY_KEY.get(key)
        if not cat:
            continue
        for p in cat["paths"]:
            if os.path.exists(p):
                out.append((key, p))
    return out


def is_protected(path: str) -> bool:
    """True if deleting `path` is forbidden (system-critical or too broad)."""
    if not path:
        return True
    rp = os.path.realpath(path)
    if rp in PROTECTED_EXACT or path in PROTECTED_EXACT:
        return True
    # Refuse anything at or above a protected prefix, and the prefixes themselves.
    for pref in PROTECTED_PREFIXES:
        pref = pref.rstrip("/")
        if rp == pref or rp.startswith(pref + "/"):
            return True
    # Never allow deleting a volume root or the home directory itself.
    if rp.count("/") <= 1:
        return True
    return False
